[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 159
src_paths = ["."]

[tool.pytest.ini_options]
markers = [
    "production",
]
