
__sources_dict__ = [
        'hub.dataload.sources.ensembl',
        'hub.dataload.sources.ensembl_fungi',
        'hub.dataload.sources.ensembl_metazoa',
        'hub.dataload.sources.ensembl_plant',
        'hub.dataload.sources.ensembl_protists',
        'hub.dataload.sources.homologene',
        'hub.dataload.sources.generif',
        'hub.dataload.sources.refseq',
        'hub.dataload.sources.entrez',
        'hub.dataload.sources.uniprot',
        'hub.dataload.sources.pharmgkb',
        'hub.dataload.sources.pharos',
        'hub.dataload.sources.reporter',
        'hub.dataload.sources.ucsc',
        'hub.dataload.sources.exac',
        'hub.dataload.sources.cpdb',
        'hub.dataload.sources.reagent',
        'hub.dataload.sources.reactome',
        'hub.dataload.sources.umls',
        'hub.dataload.sources.wikipedia',
        'hub.dataload.sources.pharos',
        'hub.dataload.sources.refmicrobe',
]

